name: pypi-release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Build and publish sdist + pure wheel
        uses: serapeum-org/github-actions/actions/release/pypi@38c111084f99d5ff5f4a1e63bedce48fe33a10c0  # pypi-release/v1.5.0
        with:
          pypi-username: __token__
          pypi-password: ${{ secrets.PYPI_PUBLISH }}
          package-manager: 'pixi'
          install-groups: 'dev'
          verify-lock: 'false'
